sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
env:
  - CAM_VERSION=LATEST
  - CAM_VERSION=7.4.0
  - CAM_VERSION=7.3.0
  - CAM_VERSION=7.2.0
  - CAM_VERSION=7.1.0-Final
  - CAM_VERSION=7.0.0-Final  
install: true
script: mvn -Dcamunda-bpm.version=$CAM_VERSION